### ISSUE TITLE
Compatibility with Pi Pico or ESP32

### ISSUE THREAD

**Issue by costasvav** [sparkfun/SparkFun_ProDriver_TC78H670FTG_Arduino_Library#1] opened 2022-10-15 21:02 UTC
Hi Sparkfun team,

I am looking to drive these drivers with something a little more powerful than a simple Arduino board. Given the success of both the Pico (RP2040) and ESP32, are there plans to make it compatible with their pinouts?

Thanks!

Edit 1:
Well, it works with the Pico's pins if you simply use the same number GPIO as Digital from an Arduino.  However, it is now very choppy and almost no torque.  I am guessing the increased clock speeds are affecting the libraries?

**Comment by metanav** [comment] 2023-06-02 12:25
Can you try to reduce the clock and check if that was the cause?

**Comment by costasvav** [comment] 2023-06-02 19:03
Wouldn't that defeat the purpose of using a more powerful CPU?  Anyways, I have moved on and no longer use these motor drivers, so I can no longer do any testing.

**Comment by metanav** [comment] 2023-06-03 03:56
> Wouldn't that defeat the purpose of using a more powerful CPU? I have moved on and no longer use these motor drivers, so I can no longer do any testing.

I want to confirm that the issue is not just related to the clock speed. Regardless, I will test it myself once I receive it.

**Comment by sfe-SparkFro** [comment] 2023-06-07 16:40
I've just tested this with a RedBoard Qwiic, ESP32 RedBoard, and RPi Pico W, all behaved identically when running Example 1. Only modification I made was changing the pin numbers in the sketch (this is demonstrated in Example 10). I don't see any obvious problems when skimming through the code; it uses `delayMicroseconds()` for timing control, which should work the same on all platforms regardless of CPU clock speed. And since I can't replicate it, going to close this. Please reply or open a new issue if anyone believes there's still a problem.

**Closed as completed by sfe-SparkFro** 2023-06-07 16:40 UTC
